apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: public-apis
  description: Catálogo de APIs Públicas
spec:
  type: openapi
  lifecycle: production
  owner: api-pheny
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Public APIs
    servers:
      - url: https://api.publicapis.org/
    paths:
      /entries:
        get:
          summary: exibe uma lista de diversas APIs públicas
